parties:
  - tenantId: greenbank
    fspId: greenbank
    domain: paymenthub-ee-connector-mojaloop.paymenthub.svc.cluster.local
  - tenantId: bluebank
    fspId: bluebank
    domain: paymenthub-ee-connector-mojaloop.paymenthub.svc.cluster.local